ARG VERSION=3.7
FROM python:${VERSION}-bullseye

COPY requirements.txt requirements-dev.txt /tmp/

RUN python3 -m pip install --upgrade pip \
  && python3 -m pip install -U -r /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements.txt

ENV USER=builder
ENV HOME=/home/${USER}
ENV PATH=${HOME}/.local/bin:${PATH}
ENV PYTHONPATH=${HOME}/archivist:${PYTHONPATH}
RUN mkdir -p ${HOME}
WORKDIR ${HOME}


