ARG VERSION=3.7
FROM python:${VERSION}-bullseye

# Note that any deps installed here must also be installed in the
# github actions workflows:
#
#      .github/workflows/python-package.yml
#      .github/workflows/python-publish.yml
#
ENV DEBIAN_FRONTEND noninteractive

RUN curl -fsSOL https://taskfile.dev/install.sh \
  && sh install.sh \
  && rm -f install.sh

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

RUN apt-get update \
  && apt-get upgrade -y --no-install-recommends \
  && apt-get install -y nodejs libenchant-2-2 \
  && apt-get autoremove \
  && apt-get autoclean \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements-dev.txt /tmp/

RUN python3 -m pip install --upgrade pip \
  && python3 -m pip install -U -r /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements.txt

ENV USER=builder
ENV HOME=/home/${USER}
ENV PATH=${HOME}/.local/bin:${PATH}
ENV PYTHONPATH=${HOME}/archivist:${PYTHONPATH}
RUN mkdir -p ${HOME}
WORKDIR ${HOME}


