#!/bin/sh
#
# inserts version into python package
#
version=$(python3 setup.py --version)

cat>archivist/__init__.py <<EOF
"""Archivist SDK

   WARNING: Do **not** edit directly
   This file is auto-generated by ./scripts/version.sh
"""
__version__ = "$version"
EOF
