# This workflow configures the repository specific choices of which CI builds
# must pass in order for a build to merge. This allows a single global teraform
# configured rule to require a "well known" check in each repository. Whilst
# granting repository stakeholders the ability configure what workflows are
# appropriate to satisfy that check.
name: Merge Requires

on: [pull_request]

jobs:
  ci:
    secrets: inherit
    uses: ./.github/workflows/ci.yml

  merge-checks-ok:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: ok
        run: |
          echo "This code is mergeable"
