# This workflow configures the repository specific choices of which CI builds
# must pass in order for a build to merge. This allows a sinlge global teraform
# configured rule to require a "well known" check in each repository. Whilst
# granting repository stakeholders the ability configure what workflows are
# appropriate to satisfy that check.
name: Merge Requires
on:
  push:

jobs:
  ci:
    secrets: inherit
    uses: ./.github/workflows/ci.yml
  release:
    secrets: inherit
    uses: ./.github/workflows/package.yml

  merge-checks-ok:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: ok
        run: |
          echo "event_name=${{ github.event_name}}" 
          echo "This code is mergeable"

  release-checks-ok:
    runs-on: ubuntu-latest
    needs: [ci, release]
    steps:
      - name: ok
        run: |
          echo "event_name=${{ github.event_name}}"
          echo "This code is releasable"
