# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Quality Control

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get upgrade -y --no-install-recommends 
        sudo apt-get install -y libenchant-2-2
        sudo apt-get autoremove
        sudo apt-get autoclean
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install wheel
    - name: Run integrity checks
      run: |
        ./scripts/version.sh
        pycodestyle --format=pylint archivist examples functests unittests
        python3 -m pylint archivist examples functests unittests
        python3 -m pyright archivist
        black archivist examples unittests functests
        (cd docs && make clean && make html)
        modified=$(git status -s | wc -l)
        if [ $modified -gt 0 ]
        then
            echo "there are $modified files that must be reformatted"
            exit 1
        fi
        ./scripts/unittests.sh
    - uses: pypa/gh-action-pip-audit@v1.0.0
      with:
        inputs: requirements.txt

